In [2]:
import numpy as np
import math

In [3]:
math.sqrt((149597870700 ** 3) / (6.67430e-11 * 5.972e24))/ (60 * 60 * 24)

33543.750123822305

In [5]:
S=np.random.uniform(-max_pos,max_pos, size=(n, 4, dim))  

In [10]:
S[:20]

array([[[-0.0872965 , -0.45649003,  0.3739033 ],
        [-0.12405617,  0.22824112, -0.23222103],
        [-0.05916461, -0.67563848,  0.51107807],
        [-0.4154993 , -0.68215886, -0.68635241]],

       [[ 0.30549505, -0.13210914, -0.27386051],
        [-0.52794973,  0.76345727, -0.44209453],
        [ 0.20850007, -0.90781865, -0.43260671],
        [ 0.26085078, -0.82937482, -0.6811872 ]],

       [[-0.97960546, -0.30274897,  0.80209   ],
        [ 0.87413778,  0.62689611,  0.82913422],
        [-0.5475971 ,  0.46063686, -0.89461487],
        [ 0.00682496,  0.78388318, -0.9739882 ]],

       [[-0.0463422 ,  0.43099337,  0.29643308],
        [-0.82844598, -0.72550652, -0.0678325 ],
        [-0.17329879, -0.96893439, -0.11344261],
        [-0.35818014, -0.03088714, -0.55983326]],

       [[-0.25265541, -0.12292299, -0.59568597],
        [-0.61050454, -0.6139265 ,  0.54539792],
        [ 0.55028159, -0.96232519, -0.36675931],
        [ 0.91656066, -0.0409435 , -0.64882707]],

       [[ 

In [11]:
x= S[:20,:,0]
x

array([[-0.0872965 , -0.12405617, -0.05916461, -0.4154993 ],
       [ 0.30549505, -0.52794973,  0.20850007,  0.26085078],
       [-0.97960546,  0.87413778, -0.5475971 ,  0.00682496],
       [-0.0463422 , -0.82844598, -0.17329879, -0.35818014],
       [-0.25265541, -0.61050454,  0.55028159,  0.91656066],
       [ 0.1459567 , -0.80734643, -0.00181633,  0.65222049],
       [ 0.41148903, -0.95083779,  0.09991466,  0.26597119],
       [-0.0364468 , -0.86869179,  0.11454422,  0.69277819],
       [ 0.02841792, -0.78176485,  0.76561463, -0.37889789],
       [ 0.38680362,  0.52199594,  0.4036265 , -0.09920164],
       [ 0.00129942,  0.58579542, -0.73550298,  0.65858181],
       [-0.14287833,  0.41848219, -0.34714309,  0.47057071],
       [ 0.30373555, -0.02781931,  0.85440796, -0.38036277],
       [-0.39252257, -0.17379357, -0.05640193, -0.79586148],
       [-0.9811651 ,  0.1739851 ,  0.47611068, -0.82217094],
       [ 0.11132438,  0.24676179,  0.59229116,  0.11879939],
       [-0.80340443,  0.

In [13]:
r0 = np.zeros((n, 2 * dim))
# initial conditions
max_pos = 1
max_vel = 0.1 * max_pos
r0[:,::2] = np.random.uniform(-max_pos, max_pos, size=(n, dim))  # positions
r0[:,1::2] = np.random.uniform(-max_vel, max_vel, size=(n, dim))  # 

In [16]:
r0

array([[-0.46194255,  0.07343627,  0.50280291, -0.06227008,  0.85212886,
         0.08509269],
       [-0.38314766, -0.01396534,  0.76733913,  0.06815312, -0.5328621 ,
        -0.030637  ],
       [-0.68976009,  0.02648427,  0.58782181, -0.02623248,  0.9992487 ,
         0.02592085],
       [-0.86870061,  0.02082667,  0.63122082, -0.04528458, -0.44678496,
        -0.02096902],
       [-0.60706758, -0.09270498,  0.61028418,  0.05906791,  0.41403345,
         0.00966037],
       [ 0.31817753,  0.0156334 ,  0.22860271,  0.01909998,  0.12979415,
         0.00507133],
       [ 0.59713274, -0.01082621,  0.68724583,  0.03625858, -0.49419461,
         0.01399418],
       [ 0.19249481,  0.0984051 , -0.18604001,  0.07809824,  0.94623595,
        -0.05593017],
       [ 0.40115824, -0.05911149,  0.77557648,  0.06861847, -0.05452192,
        -0.08185966],
       [ 0.01705005, -0.0499266 ,  0.36905494, -0.08459368, -0.68537456,
        -0.02604789],
       [-0.63008815, -0.03911829,  0.80619321,  0.